name: Update README with Activity

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch last 5 commits, merges, and pushes
        id: fetch_activity
        run: |
          # Fetch the last 5 commits
          commits=$(git log -n 5 --pretty=format:"* %h - %s (%an) - %ar" --no-merges)
          merges=$(git log --merges -n 5 --pretty=format:"* %h - %s (%an) - %ar")
          echo "Commits: $commits" >> activity.txt
          echo "Merges: $merges" >> activity.txt
          echo "Activity: $commits" > activity.txt
          cat activity.txt

      - name: Update README.md
        run: |
          # Read the existing README.md
          readme_file="README.md"
          start_marker="<!--START_SECTION:activity-->"
          end_marker="<!--END_SECTION:activity-->"
          
          # Get the activity content
          activity_content=$(cat activity.txt)

          # Update the README file
          awk -v start="$start_marker" -v end="$end_marker" -v content="$activity_content" '
          BEGIN { in_section = 0 }
          {
              if ($0 ~ start) {
                  in_section = 1;
                  print;
                  print content;
                  next;
              }
              if ($0 ~ end) {
                  in_section = 0;
              }
              if (!in_section) print;
          }' "$readme_file" > temp.md && mv temp.md "$readme_file"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with latest activity" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.README_WORKFLOW_DISPLAY }} # Use your secret token here
        run: |
          git push
